# Generated by Django 4.1 on 2023-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_doctor_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
