# Generated by Django 4.1 on 2023-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_doctor_model_delete_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_model',
            name='uname',
            field=models.TextField(),
        ),
    ]
