# Generated by Django 4.1 on 2023-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_doctor_model_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
