# Generated by Django 4.1 on 2023-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.TextField()),
                ('pic', models.ImageField(upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('pic', models.ImageField(upload_to='profiles')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor_Model',
        ),
        migrations.DeleteModel(
            name='Patient_Model',
        ),
    ]
